import { NextPage } from 'next';
import Image from 'next/image';

const ExamplesPage: NextPage = () => {
  return (
    <main className='mx-auto w-[70%] max-w-4xl py-20'>
      <h2 className='mb-20 text-center text-3xl font-medium text-white'>
        {/* Preview some branding generated by our users. */}
        This feature is coming soon.
      </h2>
      <div className='container flex items-center justify-center'>
        <Image
          src='./loading-undraw.svg'
          alt='Coming soon...'
          width={300}
          height={300}
        />
      </div>
    </main>
  );
};

export default ExamplesPage;
