import { NextPage } from 'next';
import Image from 'next/image';

const ExamplesPage: NextPage = () => {
  const images = [
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
    'https://images.clerk.dev/uploaded/img_2OrJXHrjQjZoUA1eeuhGzfGkeUh.png?width=160',
  ];

  return (
    <main className='mx-auto w-[70%] max-w-4xl py-20'>
      <h2 className='mb-10 text-center text-3xl font-medium text-white'>
        Preview some branding generated by our users.
      </h2>
      {/* <section className='grid grid-cols-4 gap-6'>
        {images.map((image, index) => (
          <Image
            key={index}
            src={image}
            alt='Generated branding'
            className='rounded-xl shadow-md shadow-gray-900'
            width={100}
            height={100}
          />
        ))}
      </section> */}
    </main>
  );
};

export default ExamplesPage;
